extra-keys = [ \
  [ \
    "ESC", \
    "DRAWER", \
    "KEYBOARD", \
    { \
      "display": "^C", \
      "macro": "CTRL c" \
    }, \
    { \
      "display": "`~", \
      "key": "`", \
      "popup": { \
        "key": "~" \
      } \
    }, \
    { \
      "display": "$^", \
      "key": "$", \
      "popup": { \
        "key": "^" \
      } \
    }, \
    { \
      "display": ":;", \
      "key": ":", \
      "popup": { \
        "key": ";" \
      } \
    }, \
    { \
      "display": "\\\" '", \
      "macro": "QUOTE QUOTE LEFT", \
      "popup": { \
        "macro": "'' LEFT", \
        "display": "'" \
      } \
    }, \
    { \
      "display": "><", \
      "key": ">", \
      "popup": { \
        "key": "<" \
      } \
    }, \
    "PGUP" \
  ], \
  [ \
    { \
      "display": "TAB", \
      "key": "TAB" \
    }, \
    { \
      "display": "/ ?", \
      "key": "/", \
      "popup": { \
        "key": "?" \
      } \
    }, \
    { \
      "display": "&*", \
      "key": "&", \
      "popup": { \
        "key": "*" \
      } \
    }, \
    { \
      "display": "| \\\\", \
      "key": "|", \
      "popup": { \
        "key": "\\\\" \
      } \
    }, \
    { \
      "display": "!@", \
      "key": "!", \
      "popup": { \
        "key": "@" \
      } \
    }, \
    { \
      "display": "()", \
      "macro": "() LEFT" \
    }, \
    "HOME", \
    "UP", \
    "END", \
    "PGDN" \
  ], \
  [ \
    "CTRL", \
    "ALT", \
    { \
      "display": "=+", \
      "key": "=", \
      "popup": { \
        "key": "+" \
      } \
    }, \
    { \
      "display": "-_", \
      "key": "-", \
      "popup": { \
        "key": "_" \
      } \
    }, \
    { \
      "display": "#%", \
      "key": "#", \
      "popup": { \
        "key": "%" \
      } \
    }, \
    { \
      "display": "[{", \
      "macro": "[] LEFT", \
      "popup": { \
        "macro": "{} LEFT", \
        "display": "{}" \
      } \
    }, \
    "LEFT", \
    "DOWN", \
    "RIGHT", \
    "ENTER" \
  ] \
]
